input {
  kb_options = compose:caps,altwin:swap_alt_win
  touchpad:natural_scroll = 1
    
}

unbind = SUPER, SPACE
bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

unbind = SUPER, W
bind = SUPER, C, killactive

unbind = SUPER, RETURN
bindd = SUPER, Q, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"

unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, E
unbind = SUPER, F

bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r
bind = SUPER, F, exec, zen-browser
bind = SUPER, E, exec, omarchy-launch-or-focus-tui yazi

bind = SUPER SHIFT, S, exec, omarchy-cmd-screenshot region
