
# Bindings

unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, L
unbind = SUPER, H
unbind = SUPER, F
unbind = SUPER, W
unbind = SUPER, RETURN
unbind = SUPER, SPACE

bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r
bind = SUPER, C, killactive
bind = SUPER, Q, exec, uwsm-app -- xdg-terminal-exec
bind = SUPER, F, exec, omarchy-launch-browser
bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

# Input

input {
  kb_options = altwin:swap_alt_win
  touchpad {
    natural_scroll = true
    disable_while_typing = true
    drag_3fg = 1
  }
}

gesture = 3, horizontal, workspace

