input {
  kb_options = altwin:swap_alt_win
  touchpad {
    drag_3fg = true
    disable_while_typing = true
		natural_scroll = true
  }
}


general {
  gaps_in = 5
	gaps_out = 5
	border_size = 0
}

decoration {
  rounding = 5
}


unbind = SUPER, SPACE
bind = SUPER, SPACE,exec, omarchy-menu

unbind = SUPER, W
unbind = SUPER, C
bind = SUPER, C, killactive

unbind = SUPER, LEFT
unbind = SUPER, H
bind = SUPER, H, movefocus, l

unbind = SUPER, DOWN
unbind = SUPER, J
bind = SUPER, J, movefocus, d

unbind = SUPER, UP
unbind = SUPER, K
bind = SUPER, K, movefocus, u

unbind = SUPER, RIGHT
unbind = SUPER, L
bind = SUPER, L, movefocus, r

unbind = SUPER, RETURN
bind = SUPER,Q, exec, xdg-terminal-exec

unbind = SUPER, F
bind = SUPER,F, exec, zen-browser
